name: 🔐 Disparar build seguro do PWABuilder NetcodeBR

on:
  repository_dispatch:
    types: [gerar_apk]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Disparar workflow de build-apk.yml
        run: |
          echo "🔗 Enviando build para GitHub Actions..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_PWABUILDERNETCODBR }}" \
            https://api.github.com/repos/netcodebr/storage/actions/workflows/build-apk.yml/dispatches \
            -d '{"ref":"main","inputs":{"pwa_url":"${{ github.event.client_payload.pwa_url }}","app_name":"${{ github.event.client_payload.app_name }}","package_id":"${{ github.event.client_payload.package_id }}"}}'
